### ISSUE TITLE
Any thoughts on implementing a second angled camera for reading licence plates?

### ISSUE THREAD

**Issue by ItGetsTheRice** [pageauc/speed-camera#102]

**Comment by pageauc** [comment]
A second camera is possible and could use imagezmq similar to my panopi project https://github.com/pageauc/panopi or some other communications method to a second RPI computer with a camera of a similar setup.  
With the new bullseye raspberry pi os.  I anticipate changes once picamera2 is available using libcamera since existing picamera python library will not work on bullseye.
