### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by AbhisarAnand** [pageauc/speed-camera#48]
I downloaded the programs by using the curl method. And then I ran the speed-cam.py program by using the ./speed-cam.py. But the program gave me the error:**AttributeError: 'NoneType' object has no attribute 'shape' Segmentation fault**

I don't know how to solve this issue. I even reinstalled everything(including the os) on the raspberry pi. I still had the same error. It would be great if someone could help me.

**I have attached a picture of the error I keep getting:**
![AttributeError](https://user-images.githubusercontent.com/43190445/71566551-85620800-2a86-11ea-8850-da4318689a34.png)

**Comment by pageauc** [comment]
Looks like a problem with the pi-camera.  What version of Raspbian are you using and what model of raspberry pi.  Segmentation faults are 
Make sure the camera module is working correctly.  Try re clamping down the ribbon cable at the RPI.  
You could also try

    sudo apt-get update
    sudo apt-get upgrade
    sudo halt

Then restart RPI by cycling power off and on.
If that does not work try updating to latest rpi firmware

    sudo rpi-update

reboot to install updated firmware.

If you have a webcam you could try that and change the config.py settings.

Segmentation faults are usually due to some type of corruption either in OS/Memory/SD card/Hardware, Etc.
per above let me know model of RPI and OS version, eg buster, stretch, jessie, etc.

Regards
