### ISSUE TITLE
Feature request: htaccess for webserver

### ISSUE THREAD

**Issue by will-code-for-pizza** [pageauc/speed-camera#60]
Hi Claude,

have you ever thought about implementing access protection for the web server?
I'm thinking of classic htaccess protection.

Regards
Will

**Comment by pageauc** [comment]
You can also upload recent folder using rclone that is installed with speed camera.  For details see https://github.com/pageauc/speed-camera/wiki/Manage-rclone-Remote-Storage-File-Transfer
I upload to my google drive and view using web browser or google drive App.

Speed camera can also be used like a security camera.  Should be low false positives due to motion tracking rather than motion detection.
